name: Boot Up

on:
  push:
    branches: ["main"]
    paths:
      - '.github/workflows/bootUp.yaml'
      - 'infra/boot/**'
  pull_request:
    types: [opened, synchronize]
    paths:
      - '.github/workflows/bootUp.yaml'
      - 'infra/boot/**'

jobs:
  deploy:
    name: Deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn workspaces focus @rainbow-husky/bootstrap-infrastructure

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          role-session-name: AuthSession

      - name: Use Pulumi
        uses: pulumi/actions@v4

      - name: Set up Pulumi
        run: |
          export PULUMI_CONFIG_PASSPHRASE=
          pulumi login s3://rainbow-husky-pulumi-state

      - name: Deploy
        env:
          PULUMI_STATE_S3_BUCKET: rainbow-husky-pulumi-state
        run: |
          export PULUMI_CONFIG_PASSPHRASE=
          cd infra/boot
          export
          pulumi stack select boot -c
          pulumi up --yes