name: Reusable Service Up workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
#    secrets:
#      GH_ACTIONS_ROLE_ARN:
#        required: true

jobs:
  service:
    name: ${{inputs.name}} Service
    timeout-minutes: 15
    runs-on: ubuntu-latest
    outputs:
      api-function-name: ${{ steps.release.outputs.api-function-name }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{inputs.name}}-${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{inputs.name}}-${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
      #
      #      - name: Show folder structure
      #        run: find . -not -path '*node_modules*'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Disable telemetry
        run: ./node_modules/.bin/turbo telemetry disable

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          role-session-name: ServiceSession

      - name: Use Pulumi
        uses: pulumi/actions@v4

      - name: Set up Pulumi
        run: |
          pulumi login s3://rainbow-husky-pulumi-state

      - name: Release
        id: release
        run: |
          export PULUMI_CONFIG_PASSPHRASE=
          export PR_NUMBER=${{ github.event.pull_request.number }}
          yarn build --filter=@rainbow-husky/${{inputs.name}}-service-code
          yarn deploy --filter=@rainbow-husky/${{inputs.name}}-service-infra
    

    #      - name: Test
    #        run: yarn test
