name: Shared Up

on:
  push:
    branches: ["main"]
    paths:
      - '.github/workflows/sharedUp.yaml'
      - 'infra/shared/**'
  pull_request:
    types: [opened, synchronize]
    paths:
      - '.github/workflows/sharedUp.yaml'
      - 'infra/shared/**'
jobs:
  shared:
    name: Shared Infrastructure
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          role-session-name: AuthSession

      - name: Use Pulumi
        uses: pulumi/actions@v4

      - name: Set up Pulumi
        run: |
          pulumi login s3://rainbow-husky-pulumi-state

      - name: Release
        id: release
        env:
          PULUMI_STATE_S3_BUCKET: rainbow-husky-pulumi-state
        run: |
          export PULUMI_CONFIG_PASSPHRASE=
          export PR_NUMBER=${{ github.event.pull_request.number }}
          yarn deploy --filter=@rainbow-husky/shared-infra